/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as VouchersNewRouteImport } from './routes/vouchers.new'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as StoresNewRouteImport } from './routes/stores.new'
import { Route as ProductsNewRouteImport } from './routes/products_.new'
import { Route as ProductsEditRouteImport } from './routes/products_..edit'
import { Route as PostsNewRouteImport } from './routes/posts.new'
import { Route as OrdersNewRouteImport } from './routes/orders_.new'
import { Route as OrdersHandoverRouteImport } from './routes/orders_.handover'
import { Route as MembershipNewRouteImport } from './routes/membership_.new'
import { Route as InventoryStockRouteImport } from './routes/inventory.stock'
import { Route as InventoryImportRouteImport } from './routes/inventory.import'
import { Route as InventoryExportRouteImport } from './routes/inventory.export'
import { Route as InventoryDestroyRouteImport } from './routes/inventory.destroy'
import { Route as InventoryAuditRouteImport } from './routes/inventory.audit'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CategoriesNewRouteImport } from './routes/categories_.new'
import { Route as BannersNewRouteImport } from './routes/banners.new'
import { Route as B2bOrdersRouteImport } from './routes/b2b.orders'
import { Route as B2bInvoicesRouteImport } from './routes/b2b.invoices'
import { Route as B2bCustomersRouteImport } from './routes/b2b.customers'
import { Route as ProductsIdEditRouteImport } from './routes/products_.$id.edit'
import { Route as MembershipIdEditRouteImport } from './routes/membership_.$id.edit'
import { Route as InventoryBatchesNewRouteImport } from './routes/inventory.batches.new'
import { Route as B2bOrdersNewRouteImport } from './routes/b2b.orders_.new'
import { Route as B2bCustomersNewRouteImport } from './routes/b2b.customers_.new'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersNewRoute = VouchersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VouchersRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresNewRoute = StoresNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StoresRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEditRoute = ProductsEditRouteImport.update({
  id: '/products_/edit',
  path: '/products/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PostsRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersHandoverRoute = OrdersHandoverRouteImport.update({
  id: '/orders_/handover',
  path: '/orders/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipNewRoute = MembershipNewRouteImport.update({
  id: '/membership_/new',
  path: '/membership/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockRoute = InventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryImportRoute = InventoryImportRouteImport.update({
  id: '/inventory/import',
  path: '/inventory/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryExportRoute = InventoryExportRouteImport.update({
  id: '/inventory/export',
  path: '/inventory/export',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryDestroyRoute = InventoryDestroyRouteImport.update({
  id: '/inventory/destroy',
  path: '/inventory/destroy',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAuditRoute = InventoryAuditRouteImport.update({
  id: '/inventory/audit',
  path: '/inventory/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/categories_/new',
  path: '/categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersNewRoute = BannersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BannersRoute,
} as any)
const B2bOrdersRoute = B2bOrdersRouteImport.update({
  id: '/b2b/orders',
  path: '/b2b/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bInvoicesRoute = B2bInvoicesRouteImport.update({
  id: '/b2b/invoices',
  path: '/b2b/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bCustomersRoute = B2bCustomersRouteImport.update({
  id: '/b2b/customers',
  path: '/b2b/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/products_/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipIdEditRoute = MembershipIdEditRouteImport.update({
  id: '/membership_/$id/edit',
  path: '/membership/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBatchesNewRoute = InventoryBatchesNewRouteImport.update({
  id: '/inventory/batches/new',
  path: '/inventory/batches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bOrdersNewRoute = B2bOrdersNewRouteImport.update({
  id: '/b2b/orders_/new',
  path: '/b2b/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bCustomersNewRoute = B2bCustomersNewRouteImport.update({
  id: '/b2b/customers_/new',
  path: '/b2b/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/banners': typeof BannersRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/marketing': typeof MarketingRoute
  '/membership': typeof MembershipRoute
  '/orders': typeof OrdersRoute
  '/permissions': typeof PermissionsRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRouteWithChildren
  '/vouchers': typeof VouchersRouteWithChildren
  '/b2b/customers': typeof B2bCustomersRoute
  '/b2b/invoices': typeof B2bInvoicesRoute
  '/b2b/orders': typeof B2bOrdersRoute
  '/banners/new': typeof BannersNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/destroy': typeof InventoryDestroyRoute
  '/inventory/export': typeof InventoryExportRoute
  '/inventory/import': typeof InventoryImportRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/membership/new': typeof MembershipNewRoute
  '/orders/handover': typeof OrdersHandoverRoute
  '/orders/new': typeof OrdersNewRoute
  '/posts/new': typeof PostsNewRoute
  '/products/edit': typeof ProductsEditRoute
  '/products/new': typeof ProductsNewRoute
  '/stores/new': typeof StoresNewRoute
  '/users/new': typeof UsersNewRoute
  '/vouchers/new': typeof VouchersNewRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/b2b/customers/new': typeof B2bCustomersNewRoute
  '/b2b/orders/new': typeof B2bOrdersNewRoute
  '/inventory/batches/new': typeof InventoryBatchesNewRoute
  '/membership/$id/edit': typeof MembershipIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/banners': typeof BannersRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/marketing': typeof MarketingRoute
  '/membership': typeof MembershipRoute
  '/orders': typeof OrdersRoute
  '/permissions': typeof PermissionsRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRouteWithChildren
  '/vouchers': typeof VouchersRouteWithChildren
  '/b2b/customers': typeof B2bCustomersRoute
  '/b2b/invoices': typeof B2bInvoicesRoute
  '/b2b/orders': typeof B2bOrdersRoute
  '/banners/new': typeof BannersNewRoute
  '/categories/new': typeof CategoriesNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/destroy': typeof InventoryDestroyRoute
  '/inventory/export': typeof InventoryExportRoute
  '/inventory/import': typeof InventoryImportRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/membership/new': typeof MembershipNewRoute
  '/orders/handover': typeof OrdersHandoverRoute
  '/orders/new': typeof OrdersNewRoute
  '/posts/new': typeof PostsNewRoute
  '/products/edit': typeof ProductsEditRoute
  '/products/new': typeof ProductsNewRoute
  '/stores/new': typeof StoresNewRoute
  '/users/new': typeof UsersNewRoute
  '/vouchers/new': typeof VouchersNewRoute
  '/categories': typeof CategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/b2b/customers/new': typeof B2bCustomersNewRoute
  '/b2b/orders/new': typeof B2bOrdersNewRoute
  '/inventory/batches/new': typeof InventoryBatchesNewRoute
  '/membership/$id/edit': typeof MembershipIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/banners': typeof BannersRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/marketing': typeof MarketingRoute
  '/membership': typeof MembershipRoute
  '/orders': typeof OrdersRoute
  '/permissions': typeof PermissionsRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRouteWithChildren
  '/vouchers': typeof VouchersRouteWithChildren
  '/b2b/customers': typeof B2bCustomersRoute
  '/b2b/invoices': typeof B2bInvoicesRoute
  '/b2b/orders': typeof B2bOrdersRoute
  '/banners/new': typeof BannersNewRoute
  '/categories_/new': typeof CategoriesNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/destroy': typeof InventoryDestroyRoute
  '/inventory/export': typeof InventoryExportRoute
  '/inventory/import': typeof InventoryImportRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/membership_/new': typeof MembershipNewRoute
  '/orders_/handover': typeof OrdersHandoverRoute
  '/orders_/new': typeof OrdersNewRoute
  '/posts/new': typeof PostsNewRoute
  '/products_/edit': typeof ProductsEditRoute
  '/products_/new': typeof ProductsNewRoute
  '/stores/new': typeof StoresNewRoute
  '/users/new': typeof UsersNewRoute
  '/vouchers/new': typeof VouchersNewRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/b2b/customers_/new': typeof B2bCustomersNewRoute
  '/b2b/orders_/new': typeof B2bOrdersNewRoute
  '/inventory/batches/new': typeof InventoryBatchesNewRoute
  '/membership_/$id/edit': typeof MembershipIdEditRoute
  '/products_/$id/edit': typeof ProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliates'
    | '/auth'
    | '/banners'
    | '/customers'
    | '/marketing'
    | '/membership'
    | '/orders'
    | '/permissions'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/vouchers'
    | '/b2b/customers'
    | '/b2b/invoices'
    | '/b2b/orders'
    | '/banners/new'
    | '/categories/new'
    | '/customers/new'
    | '/inventory/audit'
    | '/inventory/destroy'
    | '/inventory/export'
    | '/inventory/import'
    | '/inventory/stock'
    | '/membership/new'
    | '/orders/handover'
    | '/orders/new'
    | '/posts/new'
    | '/products/edit'
    | '/products/new'
    | '/stores/new'
    | '/users/new'
    | '/vouchers/new'
    | '/categories/'
    | '/products/'
    | '/b2b/customers/new'
    | '/b2b/orders/new'
    | '/inventory/batches/new'
    | '/membership/$id/edit'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliates'
    | '/auth'
    | '/banners'
    | '/customers'
    | '/marketing'
    | '/membership'
    | '/orders'
    | '/permissions'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/vouchers'
    | '/b2b/customers'
    | '/b2b/invoices'
    | '/b2b/orders'
    | '/banners/new'
    | '/categories/new'
    | '/customers/new'
    | '/inventory/audit'
    | '/inventory/destroy'
    | '/inventory/export'
    | '/inventory/import'
    | '/inventory/stock'
    | '/membership/new'
    | '/orders/handover'
    | '/orders/new'
    | '/posts/new'
    | '/products/edit'
    | '/products/new'
    | '/stores/new'
    | '/users/new'
    | '/vouchers/new'
    | '/categories'
    | '/products'
    | '/b2b/customers/new'
    | '/b2b/orders/new'
    | '/inventory/batches/new'
    | '/membership/$id/edit'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/affiliates'
    | '/auth'
    | '/banners'
    | '/customers'
    | '/marketing'
    | '/membership'
    | '/orders'
    | '/permissions'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/vouchers'
    | '/b2b/customers'
    | '/b2b/invoices'
    | '/b2b/orders'
    | '/banners/new'
    | '/categories_/new'
    | '/customers/new'
    | '/inventory/audit'
    | '/inventory/destroy'
    | '/inventory/export'
    | '/inventory/import'
    | '/inventory/stock'
    | '/membership_/new'
    | '/orders_/handover'
    | '/orders_/new'
    | '/posts/new'
    | '/products_/edit'
    | '/products_/new'
    | '/stores/new'
    | '/users/new'
    | '/vouchers/new'
    | '/categories/'
    | '/products/'
    | '/b2b/customers_/new'
    | '/b2b/orders_/new'
    | '/inventory/batches/new'
    | '/membership_/$id/edit'
    | '/products_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AuthRoute: typeof AuthRoute
  BannersRoute: typeof BannersRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  MarketingRoute: typeof MarketingRoute
  MembershipRoute: typeof MembershipRoute
  OrdersRoute: typeof OrdersRoute
  PermissionsRoute: typeof PermissionsRoute
  PostsRoute: typeof PostsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRouteWithChildren
  VouchersRoute: typeof VouchersRouteWithChildren
  B2bCustomersRoute: typeof B2bCustomersRoute
  B2bInvoicesRoute: typeof B2bInvoicesRoute
  B2bOrdersRoute: typeof B2bOrdersRoute
  CategoriesNewRoute: typeof CategoriesNewRoute
  InventoryAuditRoute: typeof InventoryAuditRoute
  InventoryDestroyRoute: typeof InventoryDestroyRoute
  InventoryExportRoute: typeof InventoryExportRoute
  InventoryImportRoute: typeof InventoryImportRoute
  InventoryStockRoute: typeof InventoryStockRoute
  MembershipNewRoute: typeof MembershipNewRoute
  OrdersHandoverRoute: typeof OrdersHandoverRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ProductsEditRoute: typeof ProductsEditRoute
  ProductsNewRoute: typeof ProductsNewRoute
  UsersNewRoute: typeof UsersNewRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  B2bCustomersNewRoute: typeof B2bCustomersNewRoute
  B2bOrdersNewRoute: typeof B2bOrdersNewRoute
  InventoryBatchesNewRoute: typeof InventoryBatchesNewRoute
  MembershipIdEditRoute: typeof MembershipIdEditRoute
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers/new': {
      id: '/vouchers/new'
      path: '/new'
      fullPath: '/vouchers/new'
      preLoaderRoute: typeof VouchersNewRouteImport
      parentRoute: typeof VouchersRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/new': {
      id: '/stores/new'
      path: '/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof StoresNewRouteImport
      parentRoute: typeof StoresRoute
    }
    '/products_/new': {
      id: '/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/edit': {
      id: '/products_/edit'
      path: '/products/edit'
      fullPath: '/products/edit'
      preLoaderRoute: typeof ProductsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof PostsRoute
    }
    '/orders_/new': {
      id: '/orders_/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/handover': {
      id: '/orders_/handover'
      path: '/orders/handover'
      fullPath: '/orders/handover'
      preLoaderRoute: typeof OrdersHandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership_/new': {
      id: '/membership_/new'
      path: '/membership/new'
      fullPath: '/membership/new'
      preLoaderRoute: typeof MembershipNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock': {
      id: '/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof InventoryStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/import': {
      id: '/inventory/import'
      path: '/inventory/import'
      fullPath: '/inventory/import'
      preLoaderRoute: typeof InventoryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/export': {
      id: '/inventory/export'
      path: '/inventory/export'
      fullPath: '/inventory/export'
      preLoaderRoute: typeof InventoryExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/destroy': {
      id: '/inventory/destroy'
      path: '/inventory/destroy'
      fullPath: '/inventory/destroy'
      preLoaderRoute: typeof InventoryDestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/audit': {
      id: '/inventory/audit'
      path: '/inventory/audit'
      fullPath: '/inventory/audit'
      preLoaderRoute: typeof InventoryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/categories_/new': {
      id: '/categories_/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/new': {
      id: '/banners/new'
      path: '/new'
      fullPath: '/banners/new'
      preLoaderRoute: typeof BannersNewRouteImport
      parentRoute: typeof BannersRoute
    }
    '/b2b/orders': {
      id: '/b2b/orders'
      path: '/b2b/orders'
      fullPath: '/b2b/orders'
      preLoaderRoute: typeof B2bOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/invoices': {
      id: '/b2b/invoices'
      path: '/b2b/invoices'
      fullPath: '/b2b/invoices'
      preLoaderRoute: typeof B2bInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/customers': {
      id: '/b2b/customers'
      path: '/b2b/customers'
      fullPath: '/b2b/customers'
      preLoaderRoute: typeof B2bCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id/edit': {
      id: '/products_/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership_/$id/edit': {
      id: '/membership_/$id/edit'
      path: '/membership/$id/edit'
      fullPath: '/membership/$id/edit'
      preLoaderRoute: typeof MembershipIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/batches/new': {
      id: '/inventory/batches/new'
      path: '/inventory/batches/new'
      fullPath: '/inventory/batches/new'
      preLoaderRoute: typeof InventoryBatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/orders_/new': {
      id: '/b2b/orders_/new'
      path: '/b2b/orders/new'
      fullPath: '/b2b/orders/new'
      preLoaderRoute: typeof B2bOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/customers_/new': {
      id: '/b2b/customers_/new'
      path: '/b2b/customers/new'
      fullPath: '/b2b/customers/new'
      preLoaderRoute: typeof B2bCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BannersRouteChildren {
  BannersNewRoute: typeof BannersNewRoute
}

const BannersRouteChildren: BannersRouteChildren = {
  BannersNewRoute: BannersNewRoute,
}

const BannersRouteWithChildren =
  BannersRoute._addFileChildren(BannersRouteChildren)

interface CustomersRouteChildren {
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface PostsRouteChildren {
  PostsNewRoute: typeof PostsNewRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsNewRoute: PostsNewRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface StoresRouteChildren {
  StoresNewRoute: typeof StoresNewRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresNewRoute: StoresNewRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

interface VouchersRouteChildren {
  VouchersNewRoute: typeof VouchersNewRoute
}

const VouchersRouteChildren: VouchersRouteChildren = {
  VouchersNewRoute: VouchersNewRoute,
}

const VouchersRouteWithChildren = VouchersRoute._addFileChildren(
  VouchersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliatesRoute: AffiliatesRoute,
  AuthRoute: AuthRoute,
  BannersRoute: BannersRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  MarketingRoute: MarketingRoute,
  MembershipRoute: MembershipRoute,
  OrdersRoute: OrdersRoute,
  PermissionsRoute: PermissionsRoute,
  PostsRoute: PostsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRouteWithChildren,
  VouchersRoute: VouchersRouteWithChildren,
  B2bCustomersRoute: B2bCustomersRoute,
  B2bInvoicesRoute: B2bInvoicesRoute,
  B2bOrdersRoute: B2bOrdersRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  InventoryAuditRoute: InventoryAuditRoute,
  InventoryDestroyRoute: InventoryDestroyRoute,
  InventoryExportRoute: InventoryExportRoute,
  InventoryImportRoute: InventoryImportRoute,
  InventoryStockRoute: InventoryStockRoute,
  MembershipNewRoute: MembershipNewRoute,
  OrdersHandoverRoute: OrdersHandoverRoute,
  OrdersNewRoute: OrdersNewRoute,
  ProductsEditRoute: ProductsEditRoute,
  ProductsNewRoute: ProductsNewRoute,
  UsersNewRoute: UsersNewRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  B2bCustomersNewRoute: B2bCustomersNewRoute,
  B2bOrdersNewRoute: B2bOrdersNewRoute,
  InventoryBatchesNewRoute: InventoryBatchesNewRoute,
  MembershipIdEditRoute: MembershipIdEditRoute,
  ProductsIdEditRoute: ProductsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
